version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  backend:
    build: ./backend
    ports:
      - "5000:5000" # For Node.js
      # - "5000:5000" # For Python


# docker-compose build
# docker-compose up
#Run the container and see the output at localhost
#To push project to docker hub
# Log in to Docker Hub (if not already logged in)
# docker login
# # Tag the frontend image
# docker tag expense-tracker_fullstack-frontend yourusername/expense-tracker-frontend:latest
# # Tag the backend image
# docker tag expense-tracker_fullstack-backend yourusername/expense-tracker-backend:latest
# # Push the frontend image
# docker push yourusername/expense-tracker-frontend:latest
# # Push the backend image
# docker push yourusername/expense-tracker-backend:latest

#$ git config --global http.postBuffer 524288000, then give git push -u origin main if your file size is large
